In [2]:
import pandas as pd

import nltk

import nlpaug.augmenter.word as naw

In [3]:
nltk.download('punkt')

nltk.download('wordnet')

nltk.download('omw-1.4')

nltk.download('averaged_perceptron_tagger')

nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\navee\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\navee\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\navee\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\navee\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\navee\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

True

In [4]:
from nltk import pos_tag

from nltk.tokenize import word_tokenize

text = "I feel hopeless and lonely"

tokens = word_tokenize(text)

print(pos_tag(tokens))

[('I', 'PRP'), ('feel', 'VBP'), ('hopeless', 'JJ'), ('and', 'CC'), ('lonely', 'JJ')]

In [5]:
df=pd.read_csv("../dataset/processed_dataset.csv")

In [6]:
df.shape

(231981, 2)

In [7]:
df.head()

                                                text        class
0  ex wife threatening suiciderecently left wife ...      suicide
1  weird dont get affected compliment coming some...  non-suicide
2  finally almost never hear bad year ever swear ...  non-suicide
3                     need helpjust help im cry hard      suicide
4  im losthello name adam ive struggling year im ...      suicide

In [8]:
aug = naw.SynonymAug(
    aug_src='wordnet',
    aug_p=0.05
)

In [9]:

for i in range(5):
    print(aug.augment("I feel hopeless and lonely"))

['I feel hopeless and lone']
['I experience hopeless and lonely']
['I feel hopeless and lonely']
['I finger hopeless and lonely']
['I feel hopeless and lone']

In [10]:
sample_df = df.sample(15000, random_state=42)

In [11]:
sample_df['synthetic_text'] = sample_df['text'].apply(
    lambda x: aug.augment(x)[0]
)

In [12]:
sample_df[['text', 'synthetic_text']].head()

,text,synthetic_text
104532,get standard galactic keyboard phone wan na co...,get standard galactic keyboard phone wan na co...
172850,hate body get sick every time look mirrorevery...,hate body get sick every time look mirrorevery...
100780,save god floodwaters neck deeper deeper sink m...,save god floodwaters neck deeper deeper sink m...
132066,got nothing going mecollege difficult point do...,got nothing going mecollege difficult point do...
13452,love ultra violent light cannon yall course lo...,love ultra violent light carom yall course lov...

In [13]:
synthetic_df = pd.DataFrame({
    'text': sample_df['synthetic_text'],
    'class': sample_df['class']
})

In [14]:
augmented_df = pd.concat(
    [df, synthetic_df],
    ignore_index=True
)

In [15]:
print(augmented_df.shape)

(246981, 2)

In [16]:
augmented_df.to_csv("../dataset/augmented_dataset.csv",index=False)